services:
    - docker

env:
  global:
    - IMAGE=elpaso/qgis-testing-environment
    # - IMAGE=boundlessgeo/qgis-testing-environment
    # - IMAGE=kartoza/qgis-testing

  matrix:
    # Tags from elpaso
    # - QGIS_VERSION_TAG=release-2_8
    # - QGIS_VERSION_TAG=release-2_14
    - QGIS_VERSION_TAG=master

    # Tags from boundlessgeo
    # - QGIS_VERSION_TAG=release # Current 2.14
    # - QGIS_VERSION_TAG=master_2 # Current 2.17
    # - QGIS_VERSION_TAG=master # Current 3.0

    # Tags from kartoza
    #- QGIS_VERSION_TAG=boundlessgeo-2.14.7

language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.6"

branches:
  # Disable branch whitelist until migration to QGIS3 is completed
  #only:
  #  - master
  #  - develop
  #  - experimental

addons:
  apt:
    packages:
      - git
      - python-software-properties

before_install:
  - docker pull ${IMAGE}:${QGIS_VERSION_TAG}

install:
  - pip install --upgrade pip
  - pip install --upgrade pylint
  - pip install --upgrade pycodestyle
  - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 ${IMAGE}:${QGIS_VERSION_TAG}
  - sleep 10
  - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh redistrict"
  - docker exec -it qgis-testing-environment sh -c "pip3 install --upgrade pylint"
  - docker exec -it qgis-testing-environment sh -c "pip3 install --upgrade pycodestyle"

  - docker exec -it qgis-testing-environment sh -c "ls -la /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/redistrict/i18n/"

script:


  - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh test_suite.test_qgis3"

  - make pylint
  - make pycodestyle

# Disable notifications until migration to QGIS3 is completed
# notifications:
#   irc:
#     channels:
#       - "irc.freenode.org#inasafe"
#     use_notice: true

#   webhooks:
#     urls:
#       - https://webhooks.gitter.im/e/a021ad05fffeac7b0a92L
#       - https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHRpbWxpbnV4JTNBbWF0cml4Lm9yZy8lMjFvUHVERUVxZU5vclJxV3hLWWQlM0FtYXRyaXgub3Jn
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: always    # options: [always|never|change] default: always

#   email:
#     - tim@kartoza.com
#     - ismail@kartoza.com
#     - rizky@kartoza.com
#     - etienne@kartoza.com
#     - rohmat@kartoza.com

sudo: false
